{
    "point_cloud_range": [-15.0, -30.0, -2.0, 15.0, 30.0, 2.0],
    "class_names": [
        "car",
        "truck",
        "construction_vehicle",
        "bus",
        "trailer",
        "barrier",
        "motorcycle",
        "bicycle",
        "pedestrian",
        "traffic_cone",
    ],
    "dataset_type": "CustomNuScenesLocalMapDataset",
    "data_root": "models/experimental/MapTR/data/nuscenes/",
    "input_modality": {
        "use_lidar": false,
        "use_camera": true,
        "use_radar": false,
        "use_map": false,
        "use_external": true,
        "_cfg_text": null,
        "_filename": null,
    },
    "file_client_args": {"backend": "disk", "_cfg_text": null, "_filename": null},
    "train_pipeline": [
        {
            "type": "LoadPointsFromFile",
            "coord_type": "LIDAR",
            "load_dim": 5,
            "use_dim": 5,
            "file_client_args": {"backend": "disk", "_cfg_text": null, "_filename": null},
            "_cfg_text": null,
            "_filename": null,
        },
        {
            "type": "LoadPointsFromMultiSweeps",
            "sweeps_num": 10,
            "file_client_args": {"backend": "disk", "_cfg_text": null, "_filename": null},
            "_cfg_text": null,
            "_filename": null,
        },
        {
            "type": "LoadAnnotations3D",
            "with_bbox_3d": true,
            "with_label_3d": true,
            "_cfg_text": null,
            "_filename": null,
        },
        {
            "type": "GlobalRotScaleTrans",
            "rot_range": [-0.3925, 0.3925],
            "scale_ratio_range": [0.95, 1.05],
            "translation_std": [0, 0, 0],
            "_cfg_text": null,
            "_filename": null,
        },
        {"type": "RandomFlip3D", "flip_ratio_bev_horizontal": 0.5, "_cfg_text": null, "_filename": null},
        {
            "type": "PointsRangeFilter",
            "point_cloud_range": [-50, -50, -5, 50, 50, 3],
            "_cfg_text": null,
            "_filename": null,
        },
        {
            "type": "ObjectRangeFilter",
            "point_cloud_range": [-50, -50, -5, 50, 50, 3],
            "_cfg_text": null,
            "_filename": null,
        },
        {
            "type": "ObjectNameFilter",
            "classes": [
                "car",
                "truck",
                "trailer",
                "bus",
                "construction_vehicle",
                "bicycle",
                "motorcycle",
                "pedestrian",
                "traffic_cone",
                "barrier",
            ],
            "_cfg_text": null,
            "_filename": null,
        },
        {"type": "PointShuffle", "_cfg_text": null, "_filename": null},
        {
            "type": "DefaultFormatBundle3D",
            "class_names": [
                "car",
                "truck",
                "trailer",
                "bus",
                "construction_vehicle",
                "bicycle",
                "motorcycle",
                "pedestrian",
                "traffic_cone",
                "barrier",
            ],
            "_cfg_text": null,
            "_filename": null,
        },
        {"type": "Collect3D", "keys": ["points", "gt_bboxes_3d", "gt_labels_3d"], "_cfg_text": null, "_filename": null},
    ],
    "test_pipeline": [
        {"type": "LoadMultiViewImageFromFiles", "to_float32": true, "_cfg_text": null, "_filename": null},
        {
            "type": "NormalizeMultiviewImage",
            "mean": [123.675, 116.28, 103.53],
            "std": [58.395, 57.12, 57.375],
            "to_rgb": true,
            "_cfg_text": null,
            "_filename": null,
        },
        {
            "type": "MultiScaleFlipAug3D",
            "img_scale": [1600, 900],
            "pts_scale_ratio": 1,
            "flip": false,
            "transforms": [
                {"type": "RandomScaleImageMultiViewImage", "scales": [0.5], "_cfg_text": null, "_filename": null},
                {"type": "PadMultiViewImage", "size_divisor": 32, "_cfg_text": null, "_filename": null},
                {
                    "type": "DefaultFormatBundle3D",
                    "class_names": [
                        "car",
                        "truck",
                        "construction_vehicle",
                        "bus",
                        "trailer",
                        "barrier",
                        "motorcycle",
                        "bicycle",
                        "pedestrian",
                        "traffic_cone",
                    ],
                    "with_label": false,
                    "_cfg_text": null,
                    "_filename": null,
                },
                {"type": "CustomCollect3D", "keys": ["img"], "_cfg_text": null, "_filename": null},
            ],
            "_cfg_text": null,
            "_filename": null,
        },
    ],
    "eval_pipeline": [
        {
            "type": "LoadPointsFromFile",
            "coord_type": "LIDAR",
            "load_dim": 5,
            "use_dim": 5,
            "file_client_args": {"backend": "disk", "_cfg_text": null, "_filename": null},
            "_cfg_text": null,
            "_filename": null,
        },
        {
            "type": "LoadPointsFromMultiSweeps",
            "sweeps_num": 10,
            "file_client_args": {"backend": "disk", "_cfg_text": null, "_filename": null},
            "_cfg_text": null,
            "_filename": null,
        },
        {
            "type": "DefaultFormatBundle3D",
            "class_names": [
                "car",
                "truck",
                "trailer",
                "bus",
                "construction_vehicle",
                "bicycle",
                "motorcycle",
                "pedestrian",
                "traffic_cone",
                "barrier",
            ],
            "with_label": false,
            "_cfg_text": null,
            "_filename": null,
        },
        {"type": "Collect3D", "keys": ["points"], "_cfg_text": null, "_filename": null},
    ],
    "data": {
        "samples_per_gpu": 4,
        "workers_per_gpu": 4,
        "train": {
            "type": "NuScenesDataset_eval_modified",
            "data_root": "data/nuscenes/",
            "ann_file": "data/nuscenes/nuscenes_infos_train.pkl",
            "pipeline": [
                {
                    "type": "LoadPointsFromFile",
                    "coord_type": "LIDAR",
                    "load_dim": 5,
                    "use_dim": 5,
                    "file_client_args": {"backend": "disk", "_cfg_text": null, "_filename": null},
                    "_cfg_text": null,
                    "_filename": null,
                },
                {
                    "type": "LoadPointsFromMultiSweeps",
                    "sweeps_num": 10,
                    "file_client_args": {"backend": "disk", "_cfg_text": null, "_filename": null},
                    "_cfg_text": null,
                    "_filename": null,
                },
                {
                    "type": "LoadAnnotations3D",
                    "with_bbox_3d": true,
                    "with_label_3d": true,
                    "_cfg_text": null,
                    "_filename": null,
                },
                {
                    "type": "GlobalRotScaleTrans",
                    "rot_range": [-0.3925, 0.3925],
                    "scale_ratio_range": [0.95, 1.05],
                    "translation_std": [0, 0, 0],
                    "_cfg_text": null,
                    "_filename": null,
                },
                {"type": "RandomFlip3D", "flip_ratio_bev_horizontal": 0.5, "_cfg_text": null, "_filename": null},
                {
                    "type": "PointsRangeFilter",
                    "point_cloud_range": [-50, -50, -5, 50, 50, 3],
                    "_cfg_text": null,
                    "_filename": null,
                },
                {
                    "type": "ObjectRangeFilter",
                    "point_cloud_range": [-50, -50, -5, 50, 50, 3],
                    "_cfg_text": null,
                    "_filename": null,
                },
                {
                    "type": "ObjectNameFilter",
                    "classes": [
                        "car",
                        "truck",
                        "trailer",
                        "bus",
                        "construction_vehicle",
                        "bicycle",
                        "motorcycle",
                        "pedestrian",
                        "traffic_cone",
                        "barrier",
                    ],
                    "_cfg_text": null,
                    "_filename": null,
                },
                {"type": "PointShuffle", "_cfg_text": null, "_filename": null},
                {
                    "type": "DefaultFormatBundle3D",
                    "class_names": [
                        "car",
                        "truck",
                        "trailer",
                        "bus",
                        "construction_vehicle",
                        "bicycle",
                        "motorcycle",
                        "pedestrian",
                        "traffic_cone",
                        "barrier",
                    ],
                    "_cfg_text": null,
                    "_filename": null,
                },
                {
                    "type": "Collect3D",
                    "keys": ["points", "gt_bboxes_3d", "gt_labels_3d"],
                    "_cfg_text": null,
                    "_filename": null,
                },
            ],
            "classes": [
                "car",
                "truck",
                "trailer",
                "bus",
                "construction_vehicle",
                "bicycle",
                "motorcycle",
                "pedestrian",
                "traffic_cone",
                "barrier",
            ],
            "modality": {
                "use_lidar": false,
                "use_camera": true,
                "use_radar": false,
                "use_map": false,
                "use_external": true,
                "_cfg_text": null,
                "_filename": null,
            },
            "test_mode": false,
            "box_type_3d": "LiDAR",
            "_cfg_text": null,
            "_filename": null,
        },
        "val": {
            "type": "CustomNuScenesLocalMapDataset",
            "ann_file": "models/experimental/MapTR/data/nuscenes/nuscenes_infos_temporal_val.pkl",
            "pipeline": [
                {"type": "LoadMultiViewImageFromFiles", "to_float32": true, "_cfg_text": null, "_filename": null},
                {
                    "type": "NormalizeMultiviewImage",
                    "mean": [123.675, 116.28, 103.53],
                    "std": [58.395, 57.12, 57.375],
                    "to_rgb": true,
                    "_cfg_text": null,
                    "_filename": null,
                },
                {
                    "type": "MultiScaleFlipAug3D",
                    "img_scale": [1600, 900],
                    "pts_scale_ratio": 1,
                    "flip": false,
                    "transforms": [
                        {
                            "type": "RandomScaleImageMultiViewImage",
                            "scales": [0.5],
                            "_cfg_text": null,
                            "_filename": null,
                        },
                        {"type": "PadMultiViewImage", "size_divisor": 32, "_cfg_text": null, "_filename": null},
                        {
                            "type": "DefaultFormatBundle3D",
                            "class_names": [
                                "car",
                                "truck",
                                "construction_vehicle",
                                "bus",
                                "trailer",
                                "barrier",
                                "motorcycle",
                                "bicycle",
                                "pedestrian",
                                "traffic_cone",
                            ],
                            "with_label": false,
                            "_cfg_text": null,
                            "_filename": null,
                        },
                        {"type": "CustomCollect3D", "keys": ["img"], "_cfg_text": null, "_filename": null},
                    ],
                    "_cfg_text": null,
                    "_filename": null,
                },
            ],
            "classes": [
                "car",
                "truck",
                "construction_vehicle",
                "bus",
                "trailer",
                "barrier",
                "motorcycle",
                "bicycle",
                "pedestrian",
                "traffic_cone",
            ],
            "modality": {
                "use_lidar": false,
                "use_camera": true,
                "use_radar": false,
                "use_map": false,
                "use_external": true,
                "_cfg_text": null,
                "_filename": null,
            },
            "test_mode": true,
            "box_type_3d": "LiDAR",
            "data_root": "models/experimental/MapTR/data/nuscenes/",
            "map_ann_file": "models/experimental/MapTR/data/nuscenes/nuscenes_map_anns_val.json",
            "bev_size": [200, 100],
            "pc_range": [-15.0, -30.0, -2.0, 15.0, 30.0, 2.0],
            "fixed_ptsnum_per_line": 20,
            "eval_use_same_gt_sample_num_flag": true,
            "padding_value": -10000,
            "map_classes": ["divider", "ped_crossing", "boundary"],
            "samples_per_gpu": 1,
            "_cfg_text": null,
            "_filename": null,
        },
        "test": {
            "type": "CustomNuScenesLocalMapDataset",
            "data_root": "models/experimental/MapTR/data/nuscenes/",
            "ann_file": "models/experimental/MapTR/data/nuscenes/nuscenes_infos_temporal_val.pkl",
            "pipeline": [
                {"type": "LoadMultiViewImageFromFiles", "to_float32": true, "_cfg_text": null, "_filename": null},
                {
                    "type": "NormalizeMultiviewImage",
                    "mean": [123.675, 116.28, 103.53],
                    "std": [58.395, 57.12, 57.375],
                    "to_rgb": true,
                    "_cfg_text": null,
                    "_filename": null,
                },
                {
                    "type": "MultiScaleFlipAug3D",
                    "img_scale": [1600, 900],
                    "pts_scale_ratio": 1,
                    "flip": false,
                    "transforms": [
                        {
                            "type": "RandomScaleImageMultiViewImage",
                            "scales": [0.5],
                            "_cfg_text": null,
                            "_filename": null,
                        },
                        {"type": "PadMultiViewImage", "size_divisor": 32, "_cfg_text": null, "_filename": null},
                        {
                            "type": "DefaultFormatBundle3D",
                            "class_names": [
                                "car",
                                "truck",
                                "construction_vehicle",
                                "bus",
                                "trailer",
                                "barrier",
                                "motorcycle",
                                "bicycle",
                                "pedestrian",
                                "traffic_cone",
                            ],
                            "with_label": false,
                            "_cfg_text": null,
                            "_filename": null,
                        },
                        {"type": "CustomCollect3D", "keys": ["img"], "_cfg_text": null, "_filename": null},
                    ],
                    "_cfg_text": null,
                    "_filename": null,
                },
            ],
            "classes": [
                "car",
                "truck",
                "construction_vehicle",
                "bus",
                "trailer",
                "barrier",
                "motorcycle",
                "bicycle",
                "pedestrian",
                "traffic_cone",
            ],
            "modality": {
                "use_lidar": false,
                "use_camera": true,
                "use_radar": false,
                "use_map": false,
                "use_external": true,
                "_cfg_text": null,
                "_filename": null,
            },
            "test_mode": true,
            "box_type_3d": "LiDAR",
            "map_ann_file": "models/experimental/MapTR/data/nuscenes/nuscenes_map_anns_val.json",
            "bev_size": [200, 100],
            "pc_range": [-15.0, -30.0, -2.0, 15.0, 30.0, 2.0],
            "fixed_ptsnum_per_line": 20,
            "eval_use_same_gt_sample_num_flag": true,
            "padding_value": -10000,
            "map_classes": ["divider", "ped_crossing", "boundary"],
            "_cfg_text": null,
            "_filename": null,
        },
        "shuffler_sampler": {"type": "DistributedGroupSampler", "_cfg_text": null, "_filename": null},
        "nonshuffler_sampler": {"type": "DistributedSampler", "_cfg_text": null, "_filename": null},
        "_cfg_text": null,
        "_filename": null,
    },
    "evaluation": {
        "interval": 1,
        "pipeline": [
            {"type": "LoadMultiViewImageFromFiles", "to_float32": true, "_cfg_text": null, "_filename": null},
            {
                "type": "NormalizeMultiviewImage",
                "mean": [123.675, 116.28, 103.53],
                "std": [58.395, 57.12, 57.375],
                "to_rgb": true,
                "_cfg_text": null,
                "_filename": null,
            },
            {
                "type": "MultiScaleFlipAug3D",
                "img_scale": [1600, 900],
                "pts_scale_ratio": 1,
                "flip": false,
                "transforms": [
                    {"type": "RandomScaleImageMultiViewImage", "scales": [0.5], "_cfg_text": null, "_filename": null},
                    {"type": "PadMultiViewImage", "size_divisor": 32, "_cfg_text": null, "_filename": null},
                    {
                        "type": "DefaultFormatBundle3D",
                        "class_names": [
                            "car",
                            "truck",
                            "construction_vehicle",
                            "bus",
                            "trailer",
                            "barrier",
                            "motorcycle",
                            "bicycle",
                            "pedestrian",
                            "traffic_cone",
                        ],
                        "with_label": false,
                        "_cfg_text": null,
                        "_filename": null,
                    },
                    {"type": "CustomCollect3D", "keys": ["img"], "_cfg_text": null, "_filename": null},
                ],
                "_cfg_text": null,
                "_filename": null,
            },
        ],
        "_cfg_text": null,
        "_filename": null,
    },
    "checkpoint_config": {"interval": 1, "_cfg_text": null, "_filename": null},
    "log_config": {
        "interval": 50,
        "hooks": [
            {"type": "TextLoggerHook", "_cfg_text": null, "_filename": null},
            {"type": "TensorboardLoggerHook", "_cfg_text": null, "_filename": null},
        ],
        "_cfg_text": null,
        "_filename": null,
    },
    "dist_params": {"backend": "nccl", "_cfg_text": null, "_filename": null},
    "log_level": "INFO",
    "work_dir": null,
    "load_from": null,
    "resume_from": null,
    "workflow": [["train", 1]],
    "plugin": true,
    "plugin_dir": "projects/mmdet3d_plugin/",
    "voxel_size": [0.15, 0.15, 4],
    "img_norm_cfg": {
        "mean": [123.675, 116.28, 103.53],
        "std": [58.395, 57.12, 57.375],
        "to_rgb": true,
        "_cfg_text": null,
        "_filename": null,
    },
    "map_classes": ["divider", "ped_crossing", "boundary"],
    "fixed_ptsnum_per_gt_line": 20,
    "fixed_ptsnum_per_pred_line": 20,
    "eval_use_same_gt_sample_num_flag": true,
    "num_map_classes": 3,
    "_dim_": 256,
    "_pos_dim_": 128,
    "_ffn_dim_": 512,
    "_num_levels_": 1,
    "bev_h_": 200,
    "bev_w_": 100,
    "queue_length": 1,
    "model": {
        "type": "MapTR",
        "use_grid_mask": true,
        "video_test_mode": false,
        "pretrained": null,
        "img_backbone": {
            "type": "ResNet",
            "depth": 50,
            "num_stages": 4,
            "out_indices": [3],
            "frozen_stages": 1,
            "norm_cfg": {"type": "BN", "requires_grad": false, "_cfg_text": null, "_filename": null},
            "norm_eval": true,
            "style": "pytorch",
            "_cfg_text": null,
            "_filename": null,
        },
        "img_neck": {
            "type": "FPN",
            "in_channels": [2048],
            "out_channels": 256,
            "start_level": 0,
            "add_extra_convs": "on_output",
            "num_outs": 1,
            "relu_before_extra_convs": true,
            "_cfg_text": null,
            "_filename": null,
        },
        "pts_bbox_head": {
            "type": "MapTRHead",
            "bev_h": 200,
            "bev_w": 100,
            "num_query": 900,
            "num_vec": 50,
            "num_pts_per_vec": 20,
            "num_pts_per_gt_vec": 20,
            "dir_interval": 1,
            "query_embed_type": "instance_pts",
            "transform_method": "minmax",
            "gt_shift_pts_pattern": "v2",
            "num_classes": 3,
            "in_channels": 256,
            "sync_cls_avg_factor": true,
            "with_box_refine": true,
            "as_two_stage": false,
            "code_size": 2,
            "code_weights": [1.0, 1.0, 1.0, 1.0],
            "transformer": {
                "type": "MapTRPerceptionTransformer",
                "rotate_prev_bev": true,
                "use_shift": true,
                "use_can_bus": true,
                "embed_dims": 256,
                "encoder": {
                    "type": "BEVFormerEncoder",
                    "num_layers": 1,
                    "pc_range": [-15.0, -30.0, -2.0, 15.0, 30.0, 2.0],
                    "num_points_in_pillar": 4,
                    "return_intermediate": false,
                    "transformerlayers": {
                        "type": "BEVFormerLayer",
                        "attn_cfgs": [
                            {
                                "type": "TemporalSelfAttention",
                                "embed_dims": 256,
                                "num_levels": 1,
                                "_cfg_text": null,
                                "_filename": null,
                            },
                            {
                                "type": "SpatialCrossAttention",
                                "pc_range": [-15.0, -30.0, -2.0, 15.0, 30.0, 2.0],
                                "deformable_attention": {
                                    "type": "MSDeformableAttention3D",
                                    "embed_dims": 256,
                                    "num_points": 8,
                                    "num_levels": 1,
                                    "_cfg_text": null,
                                    "_filename": null,
                                },
                                "embed_dims": 256,
                                "_cfg_text": null,
                                "_filename": null,
                            },
                        ],
                        "feedforward_channels": 512,
                        "ffn_dropout": 0.1,
                        "operation_order": ["self_attn", "norm", "cross_attn", "norm", "ffn", "norm"],
                        "_cfg_text": null,
                        "_filename": null,
                    },
                    "_cfg_text": null,
                    "_filename": null,
                },
                "decoder": {
                    "type": "MapTRDecoder",
                    "num_layers": 6,
                    "return_intermediate": true,
                    "transformerlayers": {
                        "type": "DetrTransformerDecoderLayer",
                        "attn_cfgs": [
                            {
                                "type": "MultiheadAttention",
                                "embed_dims": 256,
                                "num_heads": 8,
                                "dropout": 0.1,
                                "_cfg_text": null,
                                "_filename": null,
                            },
                            {
                                "type": "CustomMSDeformableAttention",
                                "embed_dims": 256,
                                "num_levels": 1,
                                "_cfg_text": null,
                                "_filename": null,
                            },
                        ],
                        "feedforward_channels": 512,
                        "ffn_dropout": 0.1,
                        "operation_order": ["self_attn", "norm", "cross_attn", "norm", "ffn", "norm"],
                        "_cfg_text": null,
                        "_filename": null,
                    },
                    "_cfg_text": null,
                    "_filename": null,
                },
                "_cfg_text": null,
                "_filename": null,
            },
            "bbox_coder": {
                "type": "MapTRNMSFreeCoder",
                "post_center_range": [-20, -35, -20, -35, 20, 35, 20, 35],
                "pc_range": [-15.0, -30.0, -2.0, 15.0, 30.0, 2.0],
                "max_num": 50,
                "voxel_size": [0.15, 0.15, 4],
                "num_classes": 3,
                "_cfg_text": null,
                "_filename": null,
            },
            "positional_encoding": {
                "type": "LearnedPositionalEncoding",
                "num_feats": 128,
                "row_num_embed": 200,
                "col_num_embed": 100,
                "_cfg_text": null,
                "_filename": null,
            },
            "_cfg_text": null,
            "_filename": null,
        },
        "_cfg_text": null,
        "_filename": null,
    },
    "total_epochs": 24,
    "fp16": {"loss_scale": 512.0, "_cfg_text": null, "_filename": null},
    "_cfg_text": "/home/ubuntu/test/tt-metal/models/experimental/MapTR/projects/configs/datasets/custom_nus-3d.py\n# If point cloud range is changed, the models should also change their point\n# cloud range accordingly\npoint_cloud_range = [-50, -50, -5, 50, 50, 3]\n# For nuScenes we usually do 10-class detection\nclass_names = [\n    'car', 'truck', 'trailer', 'bus', 'construction_vehicle', 'bicycle',\n    'motorcycle', 'pedestrian', 'traffic_cone', 'barrier'\n]\ndataset_type = 'NuScenesDataset_eval_modified'\ndata_root = 'data/nuscenes/'\n# Input modality for nuScenes dataset, this is consistent with the submission\n# format which requires the information in input_modality.\ninput_modality = dict(\n    use_lidar=True,\n    use_camera=False,\n    use_radar=False,\n    use_map=False,\n    use_external=False)\nfile_client_args = dict(backend='disk')\n# Uncomment the following if use ceph or other file clients.\n# See https://mmcv.readthedocs.io/en/latest/api.html#mmcv.fileio.FileClient\n# for more details.\n# file_client_args = dict(\n#     backend='petrel',\n#     path_mapping=dict({\n#         './data/nuscenes/': 's3://nuscenes/nuscenes/',\n#         'data/nuscenes/': 's3://nuscenes/nuscenes/'\n#     }))\ntrain_pipeline = [\n    dict(\n        type='LoadPointsFromFile',\n        coord_type='LIDAR',\n        load_dim=5,\n        use_dim=5,\n        file_client_args=file_client_args),\n    dict(\n        type='LoadPointsFromMultiSweeps',\n        sweeps_num=10,\n        file_client_args=file_client_args),\n    dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True),\n    dict(\n        type='GlobalRotScaleTrans',\n        rot_range=[-0.3925, 0.3925],\n        scale_ratio_range=[0.95, 1.05],\n        translation_std=[0, 0, 0]),\n    dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),\n    dict(type='PointsRangeFilter', point_cloud_range=point_cloud_range),\n    dict(type='ObjectRangeFilter', point_cloud_range=point_cloud_range),\n    dict(type='ObjectNameFilter', classes=class_names),\n    dict(type='PointShuffle'),\n    dict(type='DefaultFormatBundle3D', class_names=class_names),\n    dict(type='Collect3D', keys=['points', 'gt_bboxes_3d', 'gt_labels_3d'])\n]\ntest_pipeline = [\n    dict(\n        type='LoadPointsFromFile',\n        coord_type='LIDAR',\n        load_dim=5,\n        use_dim=5,\n        file_client_args=file_client_args),\n    dict(\n        type='LoadPointsFromMultiSweeps',\n        sweeps_num=10,\n        file_client_args=file_client_args),\n    dict(\n        type='MultiScaleFlipAug3D',\n        img_scale=(1333, 800),\n        pts_scale_ratio=1,\n        flip=False,\n        transforms=[\n            dict(\n                type='GlobalRotScaleTrans',\n                rot_range=[0, 0],\n                scale_ratio_range=[1., 1.],\n                translation_std=[0, 0, 0]),\n            dict(type='RandomFlip3D'),\n            dict(\n                type='PointsRangeFilter', point_cloud_range=point_cloud_range),\n            dict(\n                type='DefaultFormatBundle3D',\n                class_names=class_names,\n                with_label=False),\n            dict(type='Collect3D', keys=['points'])\n        ])\n]\n# construct a pipeline for data and gt loading in show function\n# please keep its loading function consistent with test_pipeline (e.g. client)\neval_pipeline = [\n    dict(\n        type='LoadPointsFromFile',\n        coord_type='LIDAR',\n        load_dim=5,\n        use_dim=5,\n        file_client_args=file_client_args),\n    dict(\n        type='LoadPointsFromMultiSweeps',\n        sweeps_num=10,\n        file_client_args=file_client_args),\n    dict(\n        type='DefaultFormatBundle3D',\n        class_names=class_names,\n        with_label=False),\n    dict(type='Collect3D', keys=['points'])\n]\n\ndata = dict(\n    samples_per_gpu=4,\n    workers_per_gpu=4,\n    train=dict(\n        type=dataset_type,\n        data_root=data_root,\n        ann_file=data_root + 'nuscenes_infos_train.pkl',\n        pipeline=train_pipeline,\n        classes=class_names,\n        modality=input_modality,\n        test_mode=False,\n        # we use box_type_3d='LiDAR' in kitti and nuscenes dataset\n        # and box_type_3d='Depth' in sunrgbd and scannet dataset.\n        box_type_3d='LiDAR'),\n    val=dict(\n        type=dataset_type,\n        ann_file=data_root + 'nuscenes_infos_val.pkl',\n        pipeline=test_pipeline,\n        classes=class_names,\n        modality=input_modality,\n        test_mode=True,\n        box_type_3d='LiDAR'),\n    test=dict(\n        type=dataset_type,\n        data_root=data_root,\n        ann_file=data_root + 'nuscenes_infos_val.pkl',\n        pipeline=test_pipeline,\n        classes=class_names,\n        modality=input_modality,\n        test_mode=True,\n        box_type_3d='LiDAR'))\n# For nuScenes dataset, we usually evaluate the model at the end of training.\n# Since the models are trained by 24 epochs by default, we set evaluation\n# interval to be 24. Please change the interval accordingly if you do not\n# use a default schedule.\nevaluation = dict(interval=24, pipeline=eval_pipeline)\n\n/home/ubuntu/test/tt-metal/models/experimental/MapTR/projects/configs/_base_/default_runtime.py\ncheckpoint_config = dict(interval=1)\n# yapf:disable push\n# By default we use textlogger hook and tensorboard\n# For more loggers see\n# https://mmcv.readthedocs.io/en/latest/api.html#mmcv.runner.LoggerHook\nlog_config = dict(\n    interval=50,\n    hooks=[\n        dict(type='TextLoggerHook'),\n        dict(type='TensorboardLoggerHook')\n    ])\n# yapf:enable\ndist_params = dict(backend='nccl')\nlog_level = 'INFO'\nwork_dir = None\nload_from = None\nresume_from = None\nworkflow = [('train', 1)]\n\n/home/ubuntu/test/tt-metal/models/experimental/MapTR/projects/configs/maptr/maptr_tiny_r50_24e_bevformer.py\n_base_ = [\n    '../datasets/custom_nus-3d.py',\n    '../_base_/default_runtime.py'\n]\n#\nplugin = True\nplugin_dir = 'projects/mmdet3d_plugin/'\n\n# If point cloud range is changed, the models should also change their point\n# cloud range accordingly\n# point_cloud_range = [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]\npoint_cloud_range = [-15.0, -30.0, -2.0, 15.0, 30.0, 2.0]\nvoxel_size = [0.15, 0.15, 4]\n\n\n\n\nimg_norm_cfg = dict(\n    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)\n\n# For nuScenes we usually do 10-class detection\nclass_names = [\n    'car', 'truck', 'construction_vehicle', 'bus', 'trailer', 'barrier',\n    'motorcycle', 'bicycle', 'pedestrian', 'traffic_cone'\n]\n# map has classes: divider, ped_crossing, boundary\nmap_classes = ['divider', 'ped_crossing','boundary']\n# fixed_ptsnum_per_line = 20\n# map_classes = ['divider',]\nfixed_ptsnum_per_gt_line = 20 # now only support fixed_pts > 0\nfixed_ptsnum_per_pred_line = 20\neval_use_same_gt_sample_num_flag=True\nnum_map_classes = len(map_classes)\n\ninput_modality = dict(\n    use_lidar=False,\n    use_camera=True,\n    use_radar=False,\n    use_map=False,\n    use_external=True)\n\n_dim_ = 256\n_pos_dim_ = _dim_//2\n_ffn_dim_ = _dim_*2\n_num_levels_ = 1\n# bev_h_ = 50\n# bev_w_ = 50\nbev_h_ = 200\nbev_w_ = 100\nqueue_length = 1 # each sequence contains `queue_length` frames.\n\nmodel = dict(\n    type='MapTR',\n    use_grid_mask=True,\n    video_test_mode=False,\n    pretrained=dict(img='ckpts/resnet50-19c8e357.pth'),\n    img_backbone=dict(\n        type='ResNet',\n        depth=50,\n        num_stages=4,\n        out_indices=(3,),\n        frozen_stages=1,\n        norm_cfg=dict(type='BN', requires_grad=False),\n        norm_eval=True,\n        style='pytorch'),\n    img_neck=dict(\n        type='FPN',\n        in_channels=[2048],\n        out_channels=_dim_,\n        start_level=0,\n        add_extra_convs='on_output',\n        num_outs=_num_levels_,\n        relu_before_extra_convs=True),\n    pts_bbox_head=dict(\n        type='MapTRHead',\n        bev_h=bev_h_,\n        bev_w=bev_w_,\n        num_query=900,\n        num_vec=50,\n        num_pts_per_vec=fixed_ptsnum_per_pred_line, # one bbox\n        num_pts_per_gt_vec=fixed_ptsnum_per_gt_line,\n        dir_interval=1,\n        query_embed_type='instance_pts',\n        transform_method='minmax',\n        gt_shift_pts_pattern='v2',\n        num_classes=num_map_classes,\n        in_channels=_dim_,\n        sync_cls_avg_factor=True,\n        with_box_refine=True,\n        as_two_stage=False,\n        code_size=2,\n        code_weights=[1.0, 1.0, 1.0, 1.0],\n        transformer=dict(\n            type='MapTRPerceptionTransformer',\n            rotate_prev_bev=True,\n            use_shift=True,\n            use_can_bus=True,\n            embed_dims=_dim_,\n            encoder=dict(\n                type='BEVFormerEncoder',\n                num_layers=1,\n                pc_range=point_cloud_range,\n                num_points_in_pillar=4,\n                return_intermediate=False,\n                transformerlayers=dict(\n                    type='BEVFormerLayer',\n                    attn_cfgs=[\n                        dict(\n                            type='TemporalSelfAttention',\n                            embed_dims=_dim_,\n                            num_levels=1),\n                        dict(\n                            type='SpatialCrossAttention',\n                            pc_range=point_cloud_range,\n                            deformable_attention=dict(\n                                type='MSDeformableAttention3D',\n                                embed_dims=_dim_,\n                                num_points=8,\n                                num_levels=_num_levels_),\n                            embed_dims=_dim_,\n                        )\n                    ],\n                    feedforward_channels=_ffn_dim_,\n                    ffn_dropout=0.1,\n                    operation_order=('self_attn', 'norm', 'cross_attn', 'norm',\n                                     'ffn', 'norm'))),\n            decoder=dict(\n                type='MapTRDecoder',\n                num_layers=6,\n                return_intermediate=True,\n                transformerlayers=dict(\n                    type='DetrTransformerDecoderLayer',\n                    attn_cfgs=[\n                        dict(\n                            type='MultiheadAttention',\n                            embed_dims=_dim_,\n                            num_heads=8,\n                            dropout=0.1),\n                         dict(\n                            type='CustomMSDeformableAttention',\n                            embed_dims=_dim_,\n                            num_levels=1),\n                    ],\n\n                    feedforward_channels=_ffn_dim_,\n                    ffn_dropout=0.1,\n                    operation_order=('self_attn', 'norm', 'cross_attn', 'norm',\n                                     'ffn', 'norm')))),\n        bbox_coder=dict(\n            type='MapTRNMSFreeCoder',\n            # post_center_range=[-61.2, -61.2, -10.0, 61.2, 61.2, 10.0],\n            post_center_range=[-20, -35, -20, -35, 20, 35, 20, 35],\n            pc_range=point_cloud_range,\n            max_num=50,\n            voxel_size=voxel_size,\n            num_classes=num_map_classes),\n        positional_encoding=dict(\n            type='LearnedPositionalEncoding',\n            num_feats=_pos_dim_,\n            row_num_embed=bev_h_,\n            col_num_embed=bev_w_,\n            ),\n        # loss_cls=dict(\n        #     type='FocalLoss',\n        #     use_sigmoid=True,\n        #     gamma=2.0,\n        #     alpha=0.25,\n        #     loss_weight=2.0),\n        # loss_bbox=dict(type='L1Loss', loss_weight=0.0),\n        # loss_iou=dict(type='GIoULoss', loss_weight=0.0),\n        # loss_pts=dict(type='PtsL1Loss', \n        #               loss_weight=5.0),\n        # loss_dir=dict(type='PtsDirCosLoss', loss_weight=0.005)\n        ))\n    # model training and testing settings\n    # train_cfg=dict(pts=dict(\n    #     grid_size=[512, 512, 1],\n    #     voxel_size=voxel_size,\n    #     point_cloud_range=point_cloud_range,\n    #     out_size_factor=4,\n    #     assigner=dict(\n    #         type='MapTRAssigner',\n    #         cls_cost=dict(type='FocalLossCost', weight=2.0),\n    #         reg_cost=dict(type='BBoxL1Cost', weight=0.0, box_format='xywh'),\n    #         # reg_cost=dict(type='BBox3DL1Cost', weight=0.25),\n    #         # iou_cost=dict(type='IoUCost', weight=1.0), # Fake cost. This is just to make it compatible with DETR head.\n    #         iou_cost=dict(type='IoUCost', iou_mode='giou', weight=0.0),\n    #         pts_cost=dict(type='OrderedPtsL1Cost', \n    #                   weight=5),\n    #         pc_range=point_cloud_range)))\n    # )\n\ndataset_type = 'CustomNuScenesLocalMapDataset'\ndata_root = 'models/experimental/MapTR/data/nuscenes/'\nfile_client_args = dict(backend='disk')\n\n\n# train_pipeline = [\n#     dict(type='LoadMultiViewImageFromFiles', to_float32=True),\n#     dict(type='PhotoMetricDistortionMultiViewImage'),\n#     dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True, with_attr_label=False),\n#     dict(type='ObjectRangeFilter', point_cloud_range=point_cloud_range),\n#     dict(type='ObjectNameFilter', classes=class_names),\n#     dict(type='NormalizeMultiviewImage', **img_norm_cfg),\n#     dict(type='RandomScaleImageMultiViewImage', scales=[0.5]),\n#     dict(type='PadMultiViewImage', size_divisor=32),\n#     dict(type='DefaultFormatBundle3D', class_names=class_names),\n#     dict(type='CustomCollect3D', keys=['gt_bboxes_3d', 'gt_labels_3d', 'img'])\n# ]\n\ntest_pipeline = [\n    dict(type='LoadMultiViewImageFromFiles', to_float32=True),\n    dict(type='NormalizeMultiviewImage', **img_norm_cfg),\n   \n    dict(\n        type='MultiScaleFlipAug3D',\n        img_scale=(1600, 900),\n        pts_scale_ratio=1,\n        flip=False,\n        transforms=[\n            dict(type='RandomScaleImageMultiViewImage', scales=[0.5]),\n            dict(type='PadMultiViewImage', size_divisor=32),\n            dict(\n                type='DefaultFormatBundle3D',\n                class_names=class_names,\n                with_label=False),\n            dict(type='CustomCollect3D', keys=['img'])\n        ])\n]\n\ndata = dict(\n    samples_per_gpu=4,\n    workers_per_gpu=4,\n    # train=dict(\n    #     type=dataset_type,\n    #     data_root=data_root,\n    #     ann_file=data_root + 'nuscenes_infos_temporal_train.pkl',\n    #     pipeline=train_pipeline,\n    #     classes=class_names,\n    #     modality=input_modality,\n    #     test_mode=False,\n    #     use_valid_flag=True,\n    #     bev_size=(bev_h_, bev_w_),\n    #     pc_range=point_cloud_range,\n    #     fixed_ptsnum_per_line=fixed_ptsnum_per_gt_line,\n    #     eval_use_same_gt_sample_num_flag=eval_use_same_gt_sample_num_flag,\n    #     padding_value=-10000,\n    #     map_classes=map_classes,\n    #     queue_length=queue_length,\n    #     # we use box_type_3d='LiDAR' in kitti and nuscenes dataset\n    #     # and box_type_3d='Depth' in sunrgbd and scannet dataset.\n    #     box_type_3d='LiDAR'),\n    val=dict(type=dataset_type,\n             data_root=data_root,\n             ann_file=data_root + 'nuscenes_infos_temporal_val.pkl',\n             map_ann_file=data_root + 'nuscenes_map_anns_val.json',\n             pipeline=test_pipeline,  bev_size=(bev_h_, bev_w_),\n             pc_range=point_cloud_range,\n             fixed_ptsnum_per_line=fixed_ptsnum_per_gt_line,\n             eval_use_same_gt_sample_num_flag=eval_use_same_gt_sample_num_flag,\n             padding_value=-10000,\n             map_classes=map_classes,\n             classes=class_names, modality=input_modality, samples_per_gpu=1),\n    test=dict(type=dataset_type,\n              data_root=data_root,\n              ann_file=data_root + 'nuscenes_infos_temporal_val.pkl',\n              map_ann_file=data_root + 'nuscenes_map_anns_val.json',\n              pipeline=test_pipeline, bev_size=(bev_h_, bev_w_),\n              pc_range=point_cloud_range,\n              fixed_ptsnum_per_line=fixed_ptsnum_per_gt_line,\n              eval_use_same_gt_sample_num_flag=eval_use_same_gt_sample_num_flag,\n              padding_value=-10000,\n              map_classes=map_classes,\n              classes=class_names, modality=input_modality),\n    shuffler_sampler=dict(type='DistributedGroupSampler'),\n    nonshuffler_sampler=dict(type='DistributedSampler')\n)\n\n# optimizer = dict(\n#     type='AdamW',\n#     lr=6e-4,\n#     paramwise_cfg=dict(\n#         custom_keys={\n#             'img_backbone': dict(lr_mult=0.1),\n#         }),\n#     weight_decay=0.01)\n\n# optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))\n# # learning policy\n# lr_config = dict(\n#     policy='CosineAnnealing',\n#     warmup='linear',\n#     warmup_iters=500,\n#     warmup_ratio=1.0 / 3,\n#     min_lr_ratio=1e-3)\ntotal_epochs = 24\n# total_epochs = 50\nevaluation = dict(interval=1, pipeline=test_pipeline)\n# evaluation = dict(interval=2, pipeline=test_pipeline, metric='chamfer')\n\n# runner = dict(type='EpochBasedRunner', max_epochs=total_epochs)\n\nlog_config = dict(\n    interval=50,\n    hooks=[\n        dict(type='TextLoggerHook'),\n        dict(type='TensorboardLoggerHook')\n    ])\nfp16 = dict(loss_scale=512.)\ncheckpoint_config = dict(interval=1)\n",
    "_filename": "/home/ubuntu/test/tt-metal/models/experimental/MapTR/projects/configs/maptr/maptr_tiny_r50_24e_bevformer.py",
}
